/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cardioitaim.visao;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import br.com.cardioitaim.beans.BeansPaciente;
import br.com.cardioitaim.beans.ModeloTabela;
import br.com.cardioitaim.conexao.ConexaoBD;
import br.com.cardioitaim.dao.PacienteDAO;

/**
 *
 * @author valdo
 */
public class FormPaciente extends javax.swing.JFrame {

    /**
     * Creates new form FormPaciente
     */
    int flag = 1;
    int resposta;

    ConexaoBD conex = new ConexaoBD();
    BeansPaciente paciente = new BeansPaciente();
    PacienteDAO daoPaciente = new PacienteDAO();

    public FormPaciente() {
        initComponents();
        jComboBoxBairro.setSelectedItem("Nenhum");
        preencherBairro();//preenchendo campo bairro
        preencherTabela("select id_paciente, nome_paciente, cpf_paciente, convenio_paciente, telefone_paciente, celular_paciente, "
                + "nasc_paciente, nome_bairro from pacientes inner join bairros on id_bairro_paciente = id_bairro order by nome_paciente");
    }

    public void preencherBairro() {
        conex.conectar();//CONECTANDO BD
        conex.executaSql("select * from bairros order by nome_bairro");
        try {
            conex.resultSet.first();//BUSCANDO PRIMEIRO RESULTADO
            jComboBoxBairro.removeAllItems();//limpando o campo

            do {
                jComboBoxBairro.addItem(conex.resultSet.getString("nome_bairro"));
            } while (conex.resultSet.next());

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(rootPane, "Erro ao buscar os bairros " + ex.getLocalizedMessage());
        }

        conex.desconecta();//DESCONECTANDO BD
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jPanelDadosPessoais = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabelRG = new javax.swing.JLabel();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jLabelCPF = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFormattedTextFieldNasc = new javax.swing.JFormattedTextField();
        jLabelFumante = new javax.swing.JLabel();
        jComboBoxFumante = new javax.swing.JComboBox<>();
        jLabelTelefone = new javax.swing.JLabel();
        jFormattedTextFieldTelFixo = new javax.swing.JFormattedTextField();
        jLabelCel = new javax.swing.JLabel();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jLabelConvenio = new javax.swing.JLabel();
        jComboBoxConvenio = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldContato = new javax.swing.JFormattedTextField();
        jLabelObs = new javax.swing.JLabel();
        jTextFieldObs = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanelEndereco = new javax.swing.JPanel();
        jLabelRua = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumeroCasa = new javax.swing.JTextField();
        jLabelCEP = new javax.swing.JLabel();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabelBairro = new javax.swing.JLabel();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jLabelCompl = new javax.swing.JLabel();
        jTextFieldCompl = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jRadioButtonCPF = new javax.swing.JRadioButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro e Pesquisa de Pacientes Cardio Itaim");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icone_desktop.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePacientes.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jPanelDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 2, 18))); // NOI18N

        jLabelNome.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelNome.setText("Nome");

        jTextFieldNome.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jTextFieldNome.setEnabled(false);

        jLabelSexo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelSexo.setText("Sexo");

        jComboBoxSexo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Feminino", "Masculino" }));
        jComboBoxSexo.setEnabled(false);

        jLabelRG.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelRG.setText("RG");

        try {
            jFormattedTextFieldRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRG.setEnabled(false);

        jLabelCPF.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelCPF.setText("CPF");

        jFormattedTextFieldCPF.setEnabled(false);

        jLabelDataNascimento.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelDataNascimento.setText("Nascimento");

        try {
            jFormattedTextFieldNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNasc.setEnabled(false);

        jLabelFumante.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelFumante.setText("Fumante");

        jComboBoxFumante.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jComboBoxFumante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jComboBoxFumante.setEnabled(false);

        jLabelTelefone.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelTelefone.setText("Telefone");

        try {
            jFormattedTextFieldTelFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelFixo.setEnabled(false);

        jLabelCel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelCel.setText("Celular");

        try {
            jFormattedTextFieldCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCel.setEnabled(false);

        jLabelConvenio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelConvenio.setText("Convênio");

        jComboBoxConvenio.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jComboBoxConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Amil", "Amil Linha Medical", "Amil Linha Dix", "One Health", "Unimed Paulistana", "Sul América", "Bradesco Saúde", "Notre Dame Intermédica" }));
        jComboBoxConvenio.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel2.setText("Contato");

        try {
            jFormattedTextFieldContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldContato.setEnabled(false);

        jLabelObs.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelObs.setText("Observação");

        jTextFieldObs.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTextFieldObs.setEnabled(false);

        jLabelEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelEmail.setText("E-mail");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTextFieldEmail.setEnabled(false);

        javax.swing.GroupLayout jPanelDadosPessoaisLayout = new javax.swing.GroupLayout(jPanelDadosPessoais);
        jPanelDadosPessoais.setLayout(jPanelDadosPessoaisLayout);
        jPanelDadosPessoaisLayout.setHorizontalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldContato, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelObs)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldObs))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEmail)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEmail))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSexo)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSexo, 0, 201, Short.MAX_VALUE))
                    .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabelRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFumante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFumante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConvenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDadosPessoaisLayout.setVerticalGroup(
            jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPessoaisLayout.createSequentialGroup()
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexo)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRG)
                    .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNascimento)
                    .addComponent(jFormattedTextFieldNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFumante)
                    .addComponent(jComboBoxFumante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConvenio)
                    .addComponent(jComboBoxConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jFormattedTextFieldTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCel)
                    .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObs)
                    .addComponent(jTextFieldObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 2, 18))); // NOI18N

        jLabelRua.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelRua.setText("Rua");

        jTextFieldRua.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTextFieldRua.setEnabled(false);

        jLabelNumero.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelNumero.setText("Numero");

        jTextFieldNumeroCasa.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTextFieldNumeroCasa.setEnabled(false);

        jLabelCEP.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelCEP.setText("CEP");

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.setEnabled(false);

        jLabelBairro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelBairro.setText("Bairro");

        jComboBoxBairro.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum" }));
        jComboBoxBairro.setEnabled(false);

        jLabelCompl.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabelCompl.setText("Complemento");

        jTextFieldCompl.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jTextFieldCompl.setEnabled(false);

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabelRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabelBairro)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCompl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCompl)))
                .addContainerGap())
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldCEP)
                            .addComponent(jLabelCEP)
                            .addComponent(jTextFieldNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumero))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRua)
                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBairro)
                        .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCompl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonNovo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone-add_24.png"))); // NOI18N
        jButtonNovo.setText(" Novo   ");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_editar_24.png"))); // NOI18N
        jButtonEditar.setText(" Editar   ");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSalvar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_salvar_24x.png"))); // NOI18N
        jButtonSalvar.setText(" Salvar   ");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_excluir_24_1.png"))); // NOI18N
        jButtonExcluir.setText("  Excluir  ");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_cancelar24x.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCPF);
        jRadioButtonCPF.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jRadioButtonCPF.setText("CPF");
        jRadioButtonCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCPFActionPerformed(evt);
            }
        });

        jTextFieldPesquisa.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldPesquisa.setEnabled(false);
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_buscar_24.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setEnabled(false);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jButtonPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonPesquisarKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonNome);
        jRadioButtonNome.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jRadioButtonNome.setText("Nome");
        jRadioButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jRadioButtonNome)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonCPF)
                                .addGap(32, 32, 32)
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisa)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonCPF)
                    .addComponent(jRadioButtonNome))
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanelPrincipal);
        jPanelPrincipal.setBounds(10, 60, 915, 620);

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Código");
        getContentPane().add(jLabelCodigo);
        jLabelCodigo.setBounds(690, 20, 50, 30);

        jTextFieldCodigo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jTextFieldCodigo.setEnabled(false);
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(750, 20, 70, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_cadastro_pesquisa_pacientes.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 940, 690);

        setSize(new java.awt.Dimension(948, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO NOME PARA CONTINUAR!");
            jTextFieldNome.requestFocus();
        } else if (jFormattedTextFieldRG.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO RG PARA CONTINUAR!");
            jFormattedTextFieldRG.requestFocus();
        } else if (jFormattedTextFieldCPF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO CPF PARA PARA CONTINUAR!");
            jFormattedTextFieldCPF.requestFocus();
        } else if (jTextFieldRua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO RUA PARA CONTINUAR!");
            jTextFieldRua.requestFocus();
        } else if (jTextFieldNumeroCasa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "PREENCHA O CAMPO NUMERO PARA CONTINUAR!");
            jTextFieldNumeroCasa.requestFocus();

        } else if (flag == 1) {
            //Salvando paciente
            paciente.setNomePaciente(jTextFieldNome.getText());
            paciente.setSexoPaciente((String) jComboBoxSexo.getSelectedItem());
            paciente.setRGPaciente(jFormattedTextFieldRG.getText());
            paciente.setCPFPaciente(jFormattedTextFieldCPF.getText());
            paciente.setEmailPaciente(jTextFieldEmail.getText());
            paciente.setNascPaciente(jFormattedTextFieldNasc.getText());
            paciente.setFumante((String) jComboBoxFumante.getSelectedItem());
            paciente.setConvenioPaciente((String) jComboBoxConvenio.getSelectedItem());
            paciente.setTelefonePaciente(jFormattedTextFieldTelFixo.getText());
            paciente.setCelularPaciente(jFormattedTextFieldCel.getText());
            paciente.setContatoPaciente(jFormattedTextFieldContato.getText());
            paciente.setObsPaciente(jTextFieldObs.getText());
            paciente.setRuaPaciente(jTextFieldRua.getText());
            paciente.setNumeroCasaPaciente(jTextFieldNumeroCasa.getText());
            paciente.setBairroPaciente((String) jComboBoxBairro.getSelectedItem());
            paciente.setCEPPaciente(jFormattedTextFieldCEP.getText());
            paciente.setComplPaciente(jTextFieldCompl.getText());
            daoPaciente.salvar(paciente);

            //bloqueando os campos
            jTextFieldNome.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            jFormattedTextFieldRG.setEnabled(false);
            jFormattedTextFieldCPF.setEnabled(false);
            jFormattedTextFieldNasc.setEnabled(false);
            jComboBoxFumante.setEnabled(false);
            jComboBoxConvenio.setEnabled(false);
            jFormattedTextFieldTelFixo.setEnabled(false);
            jFormattedTextFieldCel.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jFormattedTextFieldContato.setEnabled(false);
            jTextFieldObs.setEnabled(false);
            //bloqueando os campos endereco
            jTextFieldRua.setEnabled(false);
            jTextFieldNumeroCasa.setEnabled(false);
            jFormattedTextFieldCEP.setEnabled(false);
            jComboBoxBairro.setEnabled(false);
            jTextFieldCompl.setEnabled(false);
            jTextFieldPesquisa.setEnabled(false);

            //Limpando os campos Dados Pessoais
            jTextFieldNome.setText("");
            jComboBoxSexo.setSelectedItem("Nenhum");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldCPF.setText("");
            jFormattedTextFieldNasc.setText("");
            jComboBoxFumante.setSelectedItem("Não");
            jComboBoxConvenio.setSelectedItem("Particular");
            jFormattedTextFieldTelFixo.setText("");
            jFormattedTextFieldCel.setText("");
            jTextFieldEmail.setText("");
            jFormattedTextFieldContato.setText("");
            jTextFieldObs.setText("");
            //limpando os campos endereco
            jTextFieldRua.setText("");
            jTextFieldNumeroCasa.setText("");
            jFormattedTextFieldCEP.setText("");
            jComboBoxBairro.setSelectedItem("Nenhum");
            jTextFieldCompl.setText("");

            //bloqueando os campos
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);

            //liberando os botoes
            jButtonNovo.setEnabled(true);

            preencherTabela("select id_paciente, nome_paciente, cpf_paciente, convenio_paciente, telefone_paciente, celular_paciente, "
                    + "nasc_paciente, nome_bairro from pacientes inner join bairros on id_bairro_paciente = id_bairro order by nome_paciente");

            dispose();

            //ALTERANDO DADOS DO PACIENTE (clicando no botao alterar)
        } else {
            paciente.setNomePaciente(jTextFieldNome.getText());
            paciente.setSexoPaciente((String) jComboBoxSexo.getSelectedItem());
            paciente.setRGPaciente(jFormattedTextFieldRG.getText());
            paciente.setCPFPaciente(jFormattedTextFieldCPF.getText());
            paciente.setEmailPaciente(jTextFieldEmail.getText());
            paciente.setNascPaciente(jFormattedTextFieldNasc.getText());
            paciente.setFumante((String) jComboBoxFumante.getSelectedItem());
            paciente.setConvenioPaciente((String) jComboBoxConvenio.getSelectedItem());
            paciente.setTelefonePaciente(jFormattedTextFieldTelFixo.getText());
            paciente.setCelularPaciente(jFormattedTextFieldCel.getText());
            paciente.setContatoPaciente(jFormattedTextFieldContato.getText());
            paciente.setObsPaciente(jTextFieldObs.getText());
            paciente.setRuaPaciente(jTextFieldRua.getText());
            paciente.setNumeroCasaPaciente(jTextFieldNumeroCasa.getText());
            paciente.setBairroPaciente((String) jComboBoxBairro.getSelectedItem());
            paciente.setCEPPaciente(jFormattedTextFieldCEP.getText());
            paciente.setComplPaciente(jTextFieldCompl.getText());
            paciente.setCodPaciente(Integer.parseInt(jTextFieldCodigo.getText()));
            daoPaciente.editar(paciente);

            preencherTabela("select id_paciente, nome_paciente, cpf_paciente, convenio_paciente, telefone_paciente, celular_paciente, "
                    + "nasc_paciente, nome_bairro from pacientes inner join bairros on id_bairro_paciente = id_bairro order by nome_paciente");

            //Limpando os campos Dados Pessoais
            jTextFieldNome.setText("");
            jComboBoxSexo.setSelectedItem("Nenhum");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldCPF.setText("");
            jFormattedTextFieldNasc.setText("");
            jComboBoxFumante.setSelectedItem("Não");
            jComboBoxConvenio.setSelectedItem("Particular");
            jFormattedTextFieldTelFixo.setText("");
            jFormattedTextFieldCel.setText("");
            jTextFieldEmail.setText("");
            jFormattedTextFieldContato.setText("");
            jTextFieldObs.setText("");
            //limpando os campos endereco
            jTextFieldRua.setText("");
            jTextFieldNumeroCasa.setText("");
            jFormattedTextFieldCEP.setText("");
            jComboBoxBairro.setSelectedItem("Nenhum");
            jTextFieldCompl.setText("");
            jTextFieldPesquisa.setText("");

            //bloqueando os campos
            jTextFieldNome.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            jFormattedTextFieldRG.setEnabled(false);
            jFormattedTextFieldCPF.setEnabled(false);
            jFormattedTextFieldNasc.setEnabled(false);
            jComboBoxFumante.setEnabled(false);
            jComboBoxConvenio.setEnabled(false);
            jFormattedTextFieldTelFixo.setEnabled(false);
            jFormattedTextFieldCel.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jFormattedTextFieldContato.setEnabled(false);
            jTextFieldObs.setEnabled(false);
            //bloqueando os campos endereco
            jTextFieldRua.setEnabled(false);
            jTextFieldNumeroCasa.setEnabled(false);
            jFormattedTextFieldCEP.setEnabled(false);
            jComboBoxBairro.setEnabled(false);
            jTextFieldCompl.setEnabled(false);
            jTextFieldPesquisa.setEnabled(false);

            //bloqueando os campos
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonPesquisar.setEnabled(false);

            //liberando os botoes
            jButtonNovo.setEnabled(true);

            //grupo de botoes
            buttonGroup1.clearSelection();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //bloqueando botoes
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        //liberando botoes
        jButtonNovo.setEnabled(true);

        //Limpando os campos Dados Pessoais
        jTextFieldNome.setText("");
        jComboBoxSexo.setSelectedItem("Nenhum");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldNasc.setText("");
        jComboBoxFumante.setSelectedItem("Não");
        jComboBoxConvenio.setSelectedItem("Particular");
        jFormattedTextFieldTelFixo.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldEmail.setText("");
        jFormattedTextFieldContato.setText("");
        jTextFieldObs.setText("");
        //limpando os campos endereco
        jTextFieldRua.setText("");
        jTextFieldNumeroCasa.setText("");
        jFormattedTextFieldCEP.setText("");
        jComboBoxBairro.setSelectedItem("Nenhum");
        jTextFieldCompl.setText("");
        jTextFieldPesquisa.setText("");

        //bloqueando os campos
        jTextFieldNome.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jComboBoxFumante.setEnabled(false);
        jComboBoxConvenio.setEnabled(false);
        jFormattedTextFieldTelFixo.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jFormattedTextFieldContato.setEnabled(false);
        jTextFieldObs.setEnabled(false);
        //bloqueando os campos endereco
        jTextFieldRua.setEnabled(false);
        jTextFieldNumeroCasa.setEnabled(false);
        jFormattedTextFieldCEP.setEnabled(false);
        jComboBoxBairro.setEnabled(false);
        jTextFieldCompl.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);

        //grupo de botoes
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        //liberando botoes
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        //bloqueando botoes
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);

        //liberando os campos
        jTextFieldNome.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jComboBoxFumante.setEnabled(true);
        jComboBoxConvenio.setEnabled(true);
        jFormattedTextFieldTelFixo.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jFormattedTextFieldContato.setEnabled(true);
        jTextFieldObs.setEnabled(true);
        //limpando os campos endereco
        jTextFieldRua.setEnabled(true);
        jTextFieldNumeroCasa.setEnabled(true);
        jFormattedTextFieldCEP.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        jTextFieldCompl.setEnabled(true);

        //Limpando os campos Dados Pessoais
        jTextFieldNome.setText("");
        jComboBoxSexo.setSelectedItem("Nenhum");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldNasc.setText("");
        jComboBoxFumante.setSelectedItem("Não");
        jComboBoxConvenio.setSelectedItem("Particular");
        jFormattedTextFieldTelFixo.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldEmail.setText("");
        jFormattedTextFieldContato.setText("");
        jTextFieldObs.setText("");
        //limpando os campos endereco
        jTextFieldRua.setText("");
        jTextFieldNumeroCasa.setText("");
        jFormattedTextFieldCEP.setText("");
        jComboBoxBairro.setSelectedItem("Nenhum");
        jTextFieldCompl.setText("");

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        //liberando botoes
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        //bloqueando botoes
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(false);
        //liberando os campos
        jTextFieldNome.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldNasc.setEnabled(true);
        jComboBoxFumante.setEnabled(true);
        jComboBoxConvenio.setEnabled(true);
        jFormattedTextFieldTelFixo.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jFormattedTextFieldContato.setEnabled(true);
        jTextFieldObs.setEnabled(true);
        //limpando os campos endereco
        jTextFieldRua.setEnabled(true);
        jTextFieldNumeroCasa.setEnabled(true);
        jFormattedTextFieldCEP.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        jTextFieldCompl.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        resposta = JOptionPane.showConfirmDialog(rootPane, "DESEJA REALMENTE EXCLUIR?");
        if (resposta == JOptionPane.YES_OPTION) {
            paciente.setCodPaciente(Integer.parseInt(jTextFieldCodigo.getText()));
            daoPaciente.excluir(paciente);
        }
        preencherTabela("select id_paciente, nome_paciente, cpf_paciente, convenio_paciente, telefone_paciente, celular_paciente, "
                + "nasc_paciente, nome_bairro from pacientes inner join bairros on id_bairro_paciente = id_bairro order by nome_paciente");

        //Limpando os campos Dados Pessoais
        jTextFieldNome.setText("");
        jComboBoxSexo.setSelectedItem("Nenhum");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldNasc.setText("");
        jComboBoxFumante.setSelectedItem("Não");
        jComboBoxConvenio.setSelectedItem("Particular");
        jFormattedTextFieldTelFixo.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldEmail.setText("");
        jFormattedTextFieldContato.setText("");
        jTextFieldObs.setText("");
        //limpando os campos endereco
        jTextFieldRua.setText("");
        jTextFieldNumeroCasa.setText("");
        jFormattedTextFieldCEP.setText("");
        jComboBoxBairro.setSelectedItem("Nenhum");
        jTextFieldCompl.setText("");

        //bloqueando botoes
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);

        //libera botoes
        //botoes radio

    }//GEN-LAST:event_jButtonExcluirActionPerformed
    public void preencherTabela(String Sql) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Id", "Nome", "CPF", "Convênio", "Telefone", "Celular", "Nascimento", "Bairro"};

        conex.conectar();
        conex.executaSql(Sql);

        try {
            conex.resultSet.first();
            do {//fazendo alteração na tabela          
                dados.add(new Object[]{conex.resultSet.getInt("id_paciente"), conex.resultSet.getString("nome_paciente"),
                    conex.resultSet.getString("cpf_paciente"), conex.resultSet.getString("convenio_paciente"), conex.resultSet.getString("telefone_paciente"),
                    conex.resultSet.getString("celular_paciente"), conex.resultSet.getString("nasc_paciente"), conex.resultSet.getString("nome_bairro")});
            } while (conex.resultSet.next());//enquanto houver dados ele ira percorrer o registro.
        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, "BUSQUE POR OUTRO MÉDICO PARA PREENCHER A TABELA!");
        }
        ModeloTabela modelotab = new ModeloTabela(dados, colunas);
        jTablePacientes.setModel(modelotab);
        //coluna 1 ID
        jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTablePacientes.getColumnModel().getColumn(0).setResizable(false); //bloqueando o redimencionamento pelo mouse
        //coluna 2 Nome
        jTablePacientes.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTablePacientes.getColumnModel().getColumn(1).setResizable(false);//bloqueando o redimencionamento pelo mouse
        //coluna 3 CPF
        jTablePacientes.getColumnModel().getColumn(2).setPreferredWidth(85);
        jTablePacientes.getColumnModel().getColumn(2).setResizable(false);//bloqueando o redimencionamento pelo mouse
        //coluna 4 Convenio
        jTablePacientes.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(3).setResizable(false);//bloqueando o redimencionamento pelo mouse
        //coluna 5 Telefone Fixo
        jTablePacientes.getColumnModel().getColumn(4).setPreferredWidth(75);
        jTablePacientes.getColumnModel().getColumn(4).setResizable(false);//bloqueando o redimencionamento pelo mouse
        //coluna 6 Celular
        jTablePacientes.getColumnModel().getColumn(5).setPreferredWidth(79);
        jTablePacientes.getColumnModel().getColumn(5).setResizable(false);//bloqueando o redimencionamento pelo mouse
        //coluna 7 Data de Nascimento
        jTablePacientes.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTablePacientes.getColumnModel().getColumn(6).setResizable(false);//bloqueando o redimencionamento pelo mouse
        //coluna 8 Bairro
        jTablePacientes.getColumnModel().getColumn(7).setPreferredWidth(102);
        jTablePacientes.getColumnModel().getColumn(7).setResizable(false);//bloqueando o redimencionamento pelo mouse

        //bloqueando a reordenação pelo mouse
        jTablePacientes.getTableHeader().setReorderingAllowed(false);
        //bloqueia o redimencionamento automatico.
        jTablePacientes.setAutoResizeMode(jTablePacientes.AUTO_RESIZE_OFF);
        jTablePacientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jTextFieldPesquisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CAMPO PESQUISA VAZIO!!");
            jTextFieldPesquisa.requestFocus();
        } else {
            if (jRadioButtonCPF.isSelected()) {
                paciente.setPesquisaCPF(jTextFieldPesquisa.getText());
                BeansPaciente paciente1 = daoPaciente.buscaPacienteCPF(paciente);

                jTextFieldCodigo.setText(String.valueOf(paciente1.getCodPaciente()));
                jTextFieldNome.setText(paciente1.getNomePaciente());
                jComboBoxSexo.setSelectedItem(paciente1.getSexoPaciente());
                jFormattedTextFieldRG.setText(paciente1.getRGPaciente());
                jFormattedTextFieldCPF.setText(paciente1.getCPFPaciente());
                jFormattedTextFieldNasc.setText(paciente1.getNascPaciente());
                jComboBoxFumante.setSelectedItem(paciente1.getFumante());
                jComboBoxFumante.setSelectedItem(paciente1.getConvenioPaciente());
                jFormattedTextFieldTelFixo.setText(paciente1.getTelefonePaciente());
                jFormattedTextFieldCel.setText(paciente1.getCelularPaciente());
                jTextFieldEmail.setText(paciente1.getEmailPaciente());
                jFormattedTextFieldContato.setText(paciente1.getContatoPaciente());
                jTextFieldObs.setText(paciente1.getObsPaciente());
                jTextFieldRua.setText(paciente1.getRuaPaciente());
                jTextFieldNumeroCasa.setText(paciente1.getNumeroCasaPaciente());
                jFormattedTextFieldCEP.setText(paciente1.getCEPPaciente());
                jComboBoxBairro.setSelectedItem(paciente1.getBairroPaciente());
                jTextFieldCompl.setText(paciente1.getComplPaciente());
            } else {
                paciente.setPesquisarNome(jTextFieldPesquisa.getText());
                BeansPaciente paciente1 = daoPaciente.buscaPacienteNome(paciente);

                jTextFieldCodigo.setText(String.valueOf(paciente1.getCodPaciente()));
                jTextFieldNome.setText(paciente1.getNomePaciente());
                jComboBoxSexo.setSelectedItem(paciente1.getSexoPaciente());
                jFormattedTextFieldRG.setText(paciente1.getRGPaciente());
                jFormattedTextFieldCPF.setText(paciente1.getCPFPaciente());
                jFormattedTextFieldNasc.setText(paciente1.getNascPaciente());
                jComboBoxFumante.setSelectedItem(paciente1.getFumante());
                jComboBoxFumante.setSelectedItem(paciente1.getConvenioPaciente());
                jFormattedTextFieldTelFixo.setText(paciente1.getTelefonePaciente());
                jFormattedTextFieldCel.setText(paciente1.getCelularPaciente());
                jTextFieldEmail.setText(paciente1.getEmailPaciente());
                jFormattedTextFieldContato.setText(paciente1.getContatoPaciente());
                jTextFieldObs.setText(paciente1.getObsPaciente());
                jTextFieldRua.setText(paciente1.getRuaPaciente());
                jTextFieldNumeroCasa.setText(paciente1.getNumeroCasaPaciente());
                jFormattedTextFieldCEP.setText(paciente1.getCEPPaciente());
                jComboBoxBairro.setSelectedItem(paciente1.getBairroPaciente());
                jTextFieldCompl.setText(paciente1.getComplPaciente());
            }
        }
        //leberando botoes
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jRadioButtonCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCPFActionPerformed
        if (jRadioButtonCPF.isSelected()) {
            jTextFieldPesquisa.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonCPFActionPerformed

    private void jRadioButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomeActionPerformed
        if (jRadioButtonNome.isSelected()) {
            jTextFieldPesquisa.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonNomeActionPerformed

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        String nome_Paciente = "" + jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 1);
        conex.conectar();
        conex.executaSql("select * from pacientes where nome_paciente ='" + nome_Paciente + "'");
        try {
            conex.resultSet.first();
            jTextFieldCodigo.setText(String.valueOf(conex.resultSet.getInt("id_paciente")));
            jTextFieldNome.setText(conex.resultSet.getString("nome_paciente"));
            jComboBoxSexo.setSelectedItem(conex.resultSet.getString("sexo_paciente"));
            jFormattedTextFieldRG.setText(conex.resultSet.getString("rg_paciente"));
            jFormattedTextFieldCPF.setText(conex.resultSet.getString("cpf_paciente"));
            jFormattedTextFieldNasc.setText(conex.resultSet.getString("nasc_paciente"));
            jComboBoxFumante.setSelectedItem(conex.resultSet.getString("fumante_paciente"));
            jComboBoxConvenio.setSelectedItem(conex.resultSet.getString("convenio_paciente"));
            jFormattedTextFieldTelFixo.setText(conex.resultSet.getString("telefone_paciente"));
            jFormattedTextFieldCel.setText(conex.resultSet.getString("celular_paciente"));
            jTextFieldEmail.setText(conex.resultSet.getString("email_paciente"));
            jFormattedTextFieldContato.setText(conex.resultSet.getString("contato_paciente"));
            jTextFieldObs.setText(conex.resultSet.getString("obs_paciente"));
            jTextFieldRua.setText(conex.resultSet.getString("rua_paciente"));
            jTextFieldNumeroCasa.setText(conex.resultSet.getString("numrua_paciente"));
            jFormattedTextFieldCEP.setText(conex.resultSet.getString("cep_paciente"));

            //conexao para buscar o bairro no jComboBox.
            ConexaoBD conexPesquisa = new ConexaoBD();
            conexPesquisa.conectar();
            conexPesquisa.executaSql("select *from bairros where id_bairro =" + conex.resultSet.getInt("id_bairro_paciente"));
            conexPesquisa.resultSet.first();
            jComboBoxBairro.setSelectedItem(conexPesquisa.resultSet.getString("nome_bairro"));
            conexPesquisa.desconecta();
            //fim da busca para o nome do bairro.
            jTextFieldCompl.setText(conex.resultSet.getString("compl_paciente"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO SELECIONAR OS DADOS!" + ex.getMessage());
        }
        //bloqueando botoes
        jButtonSalvar.setEnabled(false);

        //liberando botoes
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);

        //bloqueando os campos
        jTextFieldNome.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jFormattedTextFieldRG.setEnabled(false);
        jFormattedTextFieldCPF.setEnabled(false);
        jFormattedTextFieldNasc.setEnabled(false);
        jComboBoxFumante.setEnabled(false);
        jComboBoxConvenio.setEnabled(false);
        jFormattedTextFieldTelFixo.setEnabled(false);
        jFormattedTextFieldCel.setEnabled(false);
        jTextFieldEmail.setEnabled(false);
        jFormattedTextFieldContato.setEnabled(false);
        jTextFieldObs.setEnabled(false);
        //bloqueando os campos endereco
        jTextFieldRua.setEnabled(false);
        jTextFieldNumeroCasa.setEnabled(false);
        jFormattedTextFieldCEP.setEnabled(false);
        jComboBoxBairro.setEnabled(false);
        jTextFieldCompl.setEnabled(false);


    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextFieldPesquisa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "CAMPO PESQUISA VAZIO!!");
                jTextFieldPesquisa.requestFocus();
            } else {
                if (jRadioButtonCPF.isSelected()) {
                    paciente.setPesquisaCPF(jTextFieldPesquisa.getText());
                    BeansPaciente paciente1 = daoPaciente.buscaPacienteCPF(paciente);

                    jTextFieldCodigo.setText(String.valueOf(paciente1.getCodPaciente()));
                    jTextFieldNome.setText(paciente1.getNomePaciente());
                    jComboBoxSexo.setSelectedItem(paciente1.getSexoPaciente());
                    jFormattedTextFieldRG.setText(paciente1.getRGPaciente());
                    jFormattedTextFieldCPF.setText(paciente1.getCPFPaciente());
                    jFormattedTextFieldNasc.setText(paciente1.getNascPaciente());
                    jComboBoxFumante.setSelectedItem(paciente1.getFumante());
                    jComboBoxFumante.setSelectedItem(paciente1.getConvenioPaciente());
                    jFormattedTextFieldTelFixo.setText(paciente1.getTelefonePaciente());
                    jFormattedTextFieldCel.setText(paciente1.getCelularPaciente());
                    jTextFieldEmail.setText(paciente1.getEmailPaciente());
                    jFormattedTextFieldContato.setText(paciente1.getContatoPaciente());
                    jTextFieldObs.setText(paciente1.getObsPaciente());
                    jTextFieldRua.setText(paciente1.getRuaPaciente());
                    jTextFieldNumeroCasa.setText(paciente1.getNumeroCasaPaciente());
                    jFormattedTextFieldCEP.setText(paciente1.getCEPPaciente());
                    jComboBoxBairro.setSelectedItem(paciente1.getBairroPaciente());
                    jTextFieldCompl.setText(paciente1.getComplPaciente());
                } else {
                    paciente.setPesquisarNome(jTextFieldPesquisa.getText());
                    BeansPaciente paciente1 = daoPaciente.buscaPacienteNome(paciente);

                    jTextFieldCodigo.setText(String.valueOf(paciente1.getCodPaciente()));
                    jTextFieldNome.setText(paciente1.getNomePaciente());
                    jComboBoxSexo.setSelectedItem(paciente1.getSexoPaciente());
                    jFormattedTextFieldRG.setText(paciente1.getRGPaciente());
                    jFormattedTextFieldCPF.setText(paciente1.getCPFPaciente());
                    jFormattedTextFieldNasc.setText(paciente1.getNascPaciente());
                    jComboBoxFumante.setSelectedItem(paciente1.getFumante());
                    jComboBoxFumante.setSelectedItem(paciente1.getConvenioPaciente());
                    jFormattedTextFieldTelFixo.setText(paciente1.getTelefonePaciente());
                    jFormattedTextFieldCel.setText(paciente1.getCelularPaciente());
                    jTextFieldEmail.setText(paciente1.getEmailPaciente());
                    jFormattedTextFieldContato.setText(paciente1.getContatoPaciente());
                    jTextFieldObs.setText(paciente1.getObsPaciente());
                    jTextFieldRua.setText(paciente1.getRuaPaciente());
                    jTextFieldNumeroCasa.setText(paciente1.getNumeroCasaPaciente());
                    jFormattedTextFieldCEP.setText(paciente1.getCEPPaciente());
                    jComboBoxBairro.setSelectedItem(paciente1.getBairroPaciente());
                    jTextFieldCompl.setText(paciente1.getComplPaciente());
                }
            }
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jButtonPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPesquisarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jTextFieldPesquisa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "CAMPO PESQUISA VAZIO!!");
                jTextFieldPesquisa.requestFocus();
            } else {
                if (jRadioButtonCPF.isSelected()) {
                    paciente.setPesquisaCPF(jTextFieldPesquisa.getText());
                    BeansPaciente paciente1 = daoPaciente.buscaPacienteCPF(paciente);

                    jTextFieldCodigo.setText(String.valueOf(paciente1.getCodPaciente()));
                    jTextFieldNome.setText(paciente1.getNomePaciente());
                    jComboBoxSexo.setSelectedItem(paciente1.getSexoPaciente());
                    jFormattedTextFieldRG.setText(paciente1.getRGPaciente());
                    jFormattedTextFieldCPF.setText(paciente1.getCPFPaciente());
                    jFormattedTextFieldNasc.setText(paciente1.getNascPaciente());
                    jComboBoxFumante.setSelectedItem(paciente1.getFumante());
                    jComboBoxFumante.setSelectedItem(paciente1.getConvenioPaciente());
                    jFormattedTextFieldTelFixo.setText(paciente1.getTelefonePaciente());
                    jFormattedTextFieldCel.setText(paciente1.getCelularPaciente());
                    jTextFieldEmail.setText(paciente1.getEmailPaciente());
                    jFormattedTextFieldContato.setText(paciente1.getContatoPaciente());
                    jTextFieldObs.setText(paciente1.getObsPaciente());
                    jTextFieldRua.setText(paciente1.getRuaPaciente());
                    jTextFieldNumeroCasa.setText(paciente1.getNumeroCasaPaciente());
                    jFormattedTextFieldCEP.setText(paciente1.getCEPPaciente());
                    jComboBoxBairro.setSelectedItem(paciente1.getBairroPaciente());
                    jTextFieldCompl.setText(paciente1.getComplPaciente());
                } else {
                    paciente.setPesquisarNome(jTextFieldPesquisa.getText());
                    BeansPaciente paciente1 = daoPaciente.buscaPacienteNome(paciente);

                    jTextFieldCodigo.setText(String.valueOf(paciente1.getCodPaciente()));
                    jTextFieldNome.setText(paciente1.getNomePaciente());
                    jComboBoxSexo.setSelectedItem(paciente1.getSexoPaciente());
                    jFormattedTextFieldRG.setText(paciente1.getRGPaciente());
                    jFormattedTextFieldCPF.setText(paciente1.getCPFPaciente());
                    jFormattedTextFieldNasc.setText(paciente1.getNascPaciente());
                    jComboBoxFumante.setSelectedItem(paciente1.getFumante());
                    jComboBoxFumante.setSelectedItem(paciente1.getConvenioPaciente());
                    jFormattedTextFieldTelFixo.setText(paciente1.getTelefonePaciente());
                    jFormattedTextFieldCel.setText(paciente1.getCelularPaciente());
                    jTextFieldEmail.setText(paciente1.getEmailPaciente());
                    jFormattedTextFieldContato.setText(paciente1.getContatoPaciente());
                    jTextFieldObs.setText(paciente1.getObsPaciente());
                    jTextFieldRua.setText(paciente1.getRuaPaciente());
                    jTextFieldNumeroCasa.setText(paciente1.getNumeroCasaPaciente());
                    jFormattedTextFieldCEP.setText(paciente1.getCEPPaciente());
                    jComboBoxBairro.setSelectedItem(paciente1.getBairroPaciente());
                    jTextFieldCompl.setText(paciente1.getComplPaciente());
                }
            }
        }
    }//GEN-LAST:event_jButtonPesquisarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxBairro;
    private javax.swing.JComboBox<String> jComboBoxConvenio;
    private javax.swing.JComboBox<String> jComboBoxFumante;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldContato;
    private javax.swing.JFormattedTextField jFormattedTextFieldNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelFixo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCompl;
    private javax.swing.JLabel jLabelConvenio;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFumante;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelObs;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanelDadosPessoais;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JRadioButton jRadioButtonCPF;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCompl;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumeroCasa;
    private javax.swing.JTextField jTextFieldObs;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
