/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cardioitaim.visao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import br.com.cardioitaim.conexao.ConexaoBD;

/**
 *
 * @author rockv
 */
public class TelaPrincipalRecep extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalAdm
     */
    FormPaciente cadPaciente = new FormPaciente();//instanciando a tela de cadastro de pacientes.
    ConexaoBD conex = new ConexaoBD();
    FormAgendamento TelaAgendamento = new FormAgendamento();
    FormAgenda telaAgenda = new FormAgenda();

    public TelaPrincipalRecep(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conex.conectar();//conecta com o banco de dados
    }

    private TelaPrincipalRecep() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblTituloBemVindo = new javax.swing.JLabel();
        jButtonCadPacientes = new javax.swing.JButton();
        jLabelinfoPacientes = new javax.swing.JLabel();
        jButtonAgendamento = new javax.swing.JButton();
        jLabelInfoAgenda = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jLabelInfoPesquisar = new javax.swing.JLabel();
        jLabelAlteracaopacientes = new javax.swing.JLabel();
        jButtonDeslogar = new javax.swing.JButton();
        jLabelDeslogar = new javax.swing.JLabel();
        jLabelFundoBemVindo = new javax.swing.JLabel();
        lblTituloTelaPrincipal = new javax.swing.JLabel();
        lblIconeTelaprincipal = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelInfoUsuario = new javax.swing.JLabel();
        lblTelaFundo = new javax.swing.JLabel();
        jMenuBarra = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemPacientes = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuItemAgendamentos = new javax.swing.JMenuItem();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro e Consulta Cardio Itaim");
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icone_desktop.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setTitle("Bem-vindo");
        try {
            jInternalFrame1.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        lblTituloBemVindo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        lblTituloBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloBemVindo.setText("Selecione abaixo o que deseja fazer:");
        jInternalFrame1.getContentPane().add(lblTituloBemVindo);
        lblTituloBemVindo.setBounds(90, 20, 450, 30);

        jButtonCadPacientes.setBackground(new java.awt.Color(255, 74, 133));
        jButtonCadPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_paciente.png"))); // NOI18N
        jButtonCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacientesActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonCadPacientes);
        jButtonCadPacientes.setBounds(140, 100, 70, 70);

        jLabelinfoPacientes.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelinfoPacientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelinfoPacientes.setText("Cadastro, Pesquisa e");
        jInternalFrame1.getContentPane().add(jLabelinfoPacientes);
        jLabelinfoPacientes.setBounds(230, 110, 230, 30);

        jButtonAgendamento.setBackground(new java.awt.Color(14, 120, 134));
        jButtonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_agenda.png"))); // NOI18N
        jButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamentoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonAgendamento);
        jButtonAgendamento.setBounds(460, 100, 70, 70);

        jLabelInfoAgenda.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabelInfoAgenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoAgenda.setText("Agendamentos e Controles");
        jLabelInfoAgenda.setToolTipText("");
        jInternalFrame1.getContentPane().add(jLabelInfoAgenda);
        jLabelInfoAgenda.setBounds(550, 120, 220, 30);

        jButtonAgenda.setBackground(new java.awt.Color(255, 194, 134));
        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_agenda_60x.png"))); // NOI18N
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(140, 230, 70, 70);

        jLabelInfoPesquisar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabelInfoPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoPesquisar.setText("Agenda");
        jInternalFrame1.getContentPane().add(jLabelInfoPesquisar);
        jLabelInfoPesquisar.setBounds(230, 240, 170, 40);

        jLabelAlteracaopacientes.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelAlteracaopacientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAlteracaopacientes.setText("Alteração de Pacientes");
        jInternalFrame1.getContentPane().add(jLabelAlteracaopacientes);
        jLabelAlteracaopacientes.setBounds(230, 140, 160, 20);

        jButtonDeslogar.setBackground(new java.awt.Color(102, 204, 255));
        jButtonDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_logout.png"))); // NOI18N
        jButtonDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeslogarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonDeslogar);
        jButtonDeslogar.setBounds(460, 230, 70, 70);

        jLabelDeslogar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDeslogar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabelDeslogar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDeslogar.setText("Deslogar");
        jInternalFrame1.getContentPane().add(jLabelDeslogar);
        jLabelDeslogar.setBounds(550, 250, 80, 25);

        jLabelFundoBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_tela_bemvindo2.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabelFundoBemVindo);
        jLabelFundoBemVindo.setBounds(0, -6, 800, 390);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(40, 80, 810, 410);
        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        lblTituloTelaPrincipal.setFont(new java.awt.Font("Segoe UI Semilight", 2, 36)); // NOI18N
        lblTituloTelaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTelaPrincipal.setText("Sistema de Cadastro e Consulta");
        getContentPane().add(lblTituloTelaPrincipal);
        lblTituloTelaPrincipal.setBounds(20, 10, 570, 60);

        lblIconeTelaprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cardio_itaim_logo_principal_branco100x100.png"))); // NOI18N
        getContentPane().add(lblIconeTelaprincipal);
        lblIconeTelaprincipal.setBounds(820, -10, 100, 90);

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(70, 500, 90, 20);

        jLabelInfoUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelInfoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoUsuario.setText("Usuário:");
        getContentPane().add(jLabelInfoUsuario);
        jLabelInfoUsuario.setBounds(10, 500, 60, 20);

        lblTelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaPrincipal.jpg"))); // NOI18N
        getContentPane().add(lblTelaFundo);
        lblTelaFundo.setBounds(0, 0, 940, 530);

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jMenuItemPacientes.setText("Pacientes");
        jMenuItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPacientes);

        jMenuBarra.add(jMenuCadastro);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBemVindo.setText("Bem-Vindo");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemBemVindo);

        jMenuItemAgendamentos.setText("Agendamentos");
        jMenuItemAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentosActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemAgendamentos);

        jMenuItemAgenda.setText("Agenda");
        jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemAgenda);

        jMenuBarra.add(jMenuFerramentas);

        jMenu1.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBarra.add(jMenu1);

        setJMenuBar(jMenuBarra);

        setSize(new java.awt.Dimension(949, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // Sair do programa ao pela tela principal.
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
        // abre a tela bem vindo
        jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    private void jButtonCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacientesActionPerformed
        if (cadPaciente == null) {//evitar que a tela abra mais de uma vez.
            cadPaciente = new FormPaciente();
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        } else {
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCadPacientesActionPerformed

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed

    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jMenuItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacientesActionPerformed
        if (cadPaciente == null) {//evitar que a tela abra mais de uma vez.
            cadPaciente = new FormPaciente();
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        } else {
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemPacientesActionPerformed

    private void jButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamentoActionPerformed
        if (TelaAgendamento == null) {//evitar que a tela abra mais de uma vez.
            TelaAgendamento = new FormAgendamento();
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        } else {
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        }
    }//GEN-LAST:event_jButtonAgendamentoActionPerformed

    private void jMenuItemAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentosActionPerformed
        if (TelaAgendamento == null) {//evitar que a tela abra mais de uma vez.
            TelaAgendamento = new FormAgendamento();
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        } else {
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemAgendamentosActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        if (telaAgenda == null) {//evitar que a tela abra mais de uma vez.
            telaAgenda = new FormAgenda();
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        } else {
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed
        if (telaAgenda == null) {//evitar que a tela abra mais de uma vez.
            telaAgenda = new FormAgenda();
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        } else {
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemAgendaActionPerformed

    private void jButtonDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeslogarActionPerformed
        dispose();
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jButtonDeslogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalRecep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonAgendamento;
    private javax.swing.JButton jButtonCadPacientes;
    private javax.swing.JButton jButtonDeslogar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelAlteracaopacientes;
    private javax.swing.JLabel jLabelDeslogar;
    private javax.swing.JLabel jLabelFundoBemVindo;
    private javax.swing.JLabel jLabelInfoAgenda;
    private javax.swing.JLabel jLabelInfoPesquisar;
    private javax.swing.JLabel jLabelInfoUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelinfoPacientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemAgendamentos;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemPacientes;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JLabel lblIconeTelaprincipal;
    private javax.swing.JLabel lblTelaFundo;
    private javax.swing.JLabel lblTituloBemVindo;
    private javax.swing.JLabel lblTituloTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
