/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cardioitaim.visao;

import javax.swing.ImageIcon;
import br.com.cardioitaim.conexao.ConexaoBD;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rockv
 */
public class TelaPrincipalAdm extends javax.swing.JFrame {

    Connection conn = ConexaoBD.getConnection();
    
    /**
     * Creates new form TelaPrincipalAdm
     */
    //TELAS
    FormPaciente cadPaciente = new FormPaciente();//instanciando a tela de cadastro de pacientes.
    FormUsuario cadUsuario = new FormUsuario();//instanciando a tela de cadastro de usuario
    FormMedico cadMedico = new FormMedico();//instanciando a tela de cadastro de medico
    FormAgendamento TelaAgendamento = new FormAgendamento();
    FormAgenda telaAgenda = new FormAgenda();
    //CONEXAO COM BD.
    ConexaoBD conex = new ConexaoBD();//instanciando a classe de conecao com banco de dados
    
   
    public TelaPrincipalAdm(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conex.conectar();//conecta com o banco de dados
        
    }

    private TelaPrincipalAdm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFramePrincipal = new javax.swing.JInternalFrame();
        lblTituloBemVindo = new javax.swing.JLabel();
        jButtonCadPacientes = new javax.swing.JButton();
        jButtonDeslogar = new javax.swing.JButton();
        jLabelInfoDeslogar = new javax.swing.JLabel();
        jButtonAgendamento = new javax.swing.JButton();
        jLabelInfoAgendamento = new javax.swing.JLabel();
        jButtonCadMedicos = new javax.swing.JButton();
        jLabelInfoMedicos = new javax.swing.JLabel();
        jButtonCadUsuarios = new javax.swing.JButton();
        jLabelInfoUsuarios = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jLabelInfoAgenda = new javax.swing.JLabel();
        jLabelinfoPacientes1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFundoBemVindo = new javax.swing.JLabel();
        lblTituloTelaPrincipal = new javax.swing.JLabel();
        lblIconeTelaprincipal = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelInfoUsuario = new javax.swing.JLabel();
        lblTelaFundo = new javax.swing.JLabel();
        jMenuBarra = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemPacientes = new javax.swing.JMenuItem();
        jMenuMedicos = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuItemAgendamentos = new javax.swing.JMenuItem();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelPacientes = new javax.swing.JMenuItem();
        jMenuItemRelAgendam = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemDeslogar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro e Consulta Cardio Itaim");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icone_desktop.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFramePrincipal.setClosable(true);
        jInternalFramePrincipal.setTitle("Bem-vindo");
        try {
            jInternalFramePrincipal.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFramePrincipal.setVisible(true);
        jInternalFramePrincipal.getContentPane().setLayout(null);

        lblTituloBemVindo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 22)); // NOI18N
        lblTituloBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloBemVindo.setText("Selecione abaixo o que deseja fazer:");
        jInternalFramePrincipal.getContentPane().add(lblTituloBemVindo);
        lblTituloBemVindo.setBounds(90, 20, 450, 30);

        jButtonCadPacientes.setBackground(new java.awt.Color(255, 74, 133));
        jButtonCadPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_paciente.png"))); // NOI18N
        jButtonCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacientesActionPerformed(evt);
            }
        });
        jInternalFramePrincipal.getContentPane().add(jButtonCadPacientes);
        jButtonCadPacientes.setBounds(120, 90, 70, 70);

        jButtonDeslogar.setBackground(new java.awt.Color(102, 204, 255));
        jButtonDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_logout.png"))); // NOI18N
        jButtonDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeslogarActionPerformed(evt);
            }
        });
        jInternalFramePrincipal.getContentPane().add(jButtonDeslogar);
        jButtonDeslogar.setBounds(620, 200, 70, 70);

        jLabelInfoDeslogar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelInfoDeslogar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoDeslogar.setText("Deslogar");
        jInternalFramePrincipal.getContentPane().add(jLabelInfoDeslogar);
        jLabelInfoDeslogar.setBounds(700, 210, 80, 20);

        jButtonAgendamento.setBackground(new java.awt.Color(14, 120, 134));
        jButtonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_agenda.png"))); // NOI18N
        jButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamentoActionPerformed(evt);
            }
        });
        jInternalFramePrincipal.getContentPane().add(jButtonAgendamento);
        jButtonAgendamento.setBounds(350, 90, 70, 70);

        jLabelInfoAgendamento.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelInfoAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoAgendamento.setText("Agendamentos e Controles");
        jLabelInfoAgendamento.setToolTipText("");
        jInternalFramePrincipal.getContentPane().add(jLabelInfoAgendamento);
        jLabelInfoAgendamento.setBounds(430, 110, 180, 20);

        jButtonCadMedicos.setBackground(new java.awt.Color(255, 91, 98));
        jButtonCadMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_medico.png"))); // NOI18N
        jButtonCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicosActionPerformed(evt);
            }
        });
        jInternalFramePrincipal.getContentPane().add(jButtonCadMedicos);
        jButtonCadMedicos.setBounds(350, 200, 70, 70);

        jLabelInfoMedicos.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelInfoMedicos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoMedicos.setText("Cadastro de Médicos");
        jInternalFramePrincipal.getContentPane().add(jLabelInfoMedicos);
        jLabelInfoMedicos.setBounds(430, 220, 140, 20);

        jButtonCadUsuarios.setBackground(new java.awt.Color(255, 202, 79));
        jButtonCadUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_usuarios.png"))); // NOI18N
        jButtonCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuariosActionPerformed(evt);
            }
        });
        jInternalFramePrincipal.getContentPane().add(jButtonCadUsuarios);
        jButtonCadUsuarios.setBounds(120, 200, 70, 70);

        jLabelInfoUsuarios.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelInfoUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoUsuarios.setText("Cadastro de Usuários");
        jInternalFramePrincipal.getContentPane().add(jLabelInfoUsuarios);
        jLabelInfoUsuarios.setBounds(200, 220, 130, 20);

        jButtonAgenda.setBackground(new java.awt.Color(255, 194, 134));
        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_agenda_60x.png"))); // NOI18N
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jInternalFramePrincipal.getContentPane().add(jButtonAgenda);
        jButtonAgenda.setBounds(620, 90, 70, 70);

        jLabelInfoAgenda.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelInfoAgenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoAgenda.setText("Agenda");
        jInternalFramePrincipal.getContentPane().add(jLabelInfoAgenda);
        jLabelInfoAgenda.setBounds(710, 110, 80, 20);

        jLabelinfoPacientes1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelinfoPacientes1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelinfoPacientes1.setText("Cadastro, Pesquisa e");
        jInternalFramePrincipal.getContentPane().add(jLabelinfoPacientes1);
        jLabelinfoPacientes1.setBounds(200, 100, 130, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alteração de Pacientes");
        jInternalFramePrincipal.getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 120, 140, 20);

        jLabelFundoBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_tela_bemvindo2.png"))); // NOI18N
        jInternalFramePrincipal.getContentPane().add(jLabelFundoBemVindo);
        jLabelFundoBemVindo.setBounds(0, -6, 800, 390);

        getContentPane().add(jInternalFramePrincipal);
        jInternalFramePrincipal.setBounds(50, 80, 810, 410);
        try {
            jInternalFramePrincipal.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        lblTituloTelaPrincipal.setFont(new java.awt.Font("Segoe UI Semilight", 2, 36)); // NOI18N
        lblTituloTelaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTelaPrincipal.setText("Sistema de Cadastro e Consulta");
        getContentPane().add(lblTituloTelaPrincipal);
        lblTituloTelaPrincipal.setBounds(20, 10, 570, 60);

        lblIconeTelaprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cardio_itaim_logo_principal_branco100x100.png"))); // NOI18N
        getContentPane().add(lblIconeTelaprincipal);
        lblIconeTelaprincipal.setBounds(820, -10, 100, 90);

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(70, 500, 90, 20);

        jLabelInfoUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabelInfoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfoUsuario.setText("Usuário:");
        getContentPane().add(jLabelInfoUsuario);
        jLabelInfoUsuario.setBounds(10, 500, 60, 20);

        lblTelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaPrincipal.jpg"))); // NOI18N
        getContentPane().add(lblTelaFundo);
        lblTelaFundo.setBounds(0, 0, 940, 530);

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jMenuItemPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPacientes.setText("Pacientes");
        jMenuItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPacientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPacientes);

        jMenuMedicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuMedicos.setText("Médicos");
        jMenuMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMedicosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuMedicos);

        jMenuItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemUsuarios.setText("Usuários");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuarios);

        jMenuBarra.add(jMenuCadastro);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBemVindo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemBemVindo.setText("Bem-Vindo");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemBemVindo);

        jMenuItemAgendamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemAgendamentos.setText("Agendamentos");
        jMenuItemAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentosActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemAgendamentos);

        jMenuItemAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemAgenda.setText("Agenda");
        jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemAgenda);

        jMenuBarra.add(jMenuFerramentas);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemRelPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelPacientes.setText("Pacientes");
        jMenuItemRelPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelPacientesActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelPacientes);

        jMenuItemRelAgendam.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRelAgendam.setText("Agendamentos");
        jMenuItemRelAgendam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelAgendamActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemRelAgendam);

        jMenuBarra.add(jMenuRelatorios);

        jMenu1.setText("Sair");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuItemDeslogar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemDeslogar.setText("Deslogar");
        jMenu1.add(jMenuItemDeslogar);

        jMenuBarra.add(jMenu1);

        setJMenuBar(jMenuBarra);

        setSize(new java.awt.Dimension(949, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // Sair do programa ao pela tela principal.
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicosActionPerformed
        if (cadMedico == null) {//evitar que a tela abra mais de uma vez.
            cadMedico = new FormMedico();
            cadMedico.setVisible(true);
            cadMedico.setResizable(false);
        } else {
            cadMedico.setVisible(true);
            cadMedico.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCadMedicosActionPerformed

    private void jMenuMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedicosActionPerformed
        if (cadMedico == null) {//evitar que a tela abra mais de uma vez.
            cadMedico = new FormMedico();
            cadMedico.setVisible(true);
            cadMedico.setResizable(false);
        } else {
            cadMedico.setVisible(true);
            cadMedico.setResizable(false);
        }
    }//GEN-LAST:event_jMenuMedicosActionPerformed

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
        // abre a tela bem vindo
        jInternalFramePrincipal.setVisible(true);
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    private void jButtonCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuariosActionPerformed
        if (cadUsuario == null) {//evitar que a tela abra mais de uma vez.
            cadUsuario = new FormUsuario();
            cadUsuario.setVisible(true);
            cadUsuario.setResizable(false);
        } else {
            cadUsuario.setVisible(true);
            cadUsuario.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCadUsuariosActionPerformed

    private void jButtonCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacientesActionPerformed
        if (cadPaciente == null) {//evitar que a tela abra mais de uma vez.
            cadPaciente = new FormPaciente();
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        } else {
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        }
    }//GEN-LAST:event_jButtonCadPacientesActionPerformed

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed

    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        if (cadUsuario == null) {//evitar que a tela abra mais de uma vez.
            cadUsuario = new FormUsuario();
            cadUsuario.setVisible(true);
            cadUsuario.setResizable(false);
        } else {
            cadUsuario.setVisible(true);
            cadUsuario.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPacientesActionPerformed
        if (cadPaciente == null) {//evitar que a tela abra mais de uma vez.
            cadPaciente = new FormPaciente();
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        } else {
            cadPaciente.setVisible(true);
            cadPaciente.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemPacientesActionPerformed

    private void jButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamentoActionPerformed
        if (TelaAgendamento == null) {//evitar que a tela abra mais de uma vez.
            TelaAgendamento = new FormAgendamento();
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        } else {
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        }
    }//GEN-LAST:event_jButtonAgendamentoActionPerformed

    private void jMenuItemAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentosActionPerformed
        if (TelaAgendamento == null) {//evitar que a tela abra mais de uma vez.
            TelaAgendamento = new FormAgendamento();
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        } else {
            TelaAgendamento.setVisible(true);
            TelaAgendamento.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemAgendamentosActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        if (telaAgenda == null) {//evitar que a tela abra mais de uma vez.
            telaAgenda = new FormAgenda();
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        } else {
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed
        if (telaAgenda == null) {//evitar que a tela abra mais de uma vez.
            telaAgenda = new FormAgenda();
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        } else {
            telaAgenda.setVisible(true);
            telaAgenda.setResizable(false);
        }
    }//GEN-LAST:event_jMenuItemAgendaActionPerformed

    private void jButtonDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeslogarActionPerformed
        dispose();
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jButtonDeslogarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        dispose();
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemRelPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelPacientesActionPerformed
        // GERANDO RELATORIO DE CLIENTES
        int confirma = JOptionPane.showConfirmDialog(rootPane, "DESEJA REALMENTE IMPRIMIR?", "ATENÇÃO!",JOptionPane.YES_NO_OPTION);//confirmacao de impressao
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo relatorio com iReport
            try {
                //Usando a class JasperPrint para preparar a impressao relatorio
                JasperPrint print = JasperFillManager.fillReport("D:/NetBeansProjects/Cardio Itaim/src/br/com/cardioitaim/ireports/relPacientes.jasper",null,conn);
                //a linha abaixo exibe o relatorio atraves da classe JasperViewer
                JasperViewer.viewReport(print,false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_jMenuItemRelPacientesActionPerformed

    private void jMenuItemRelAgendamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelAgendamActionPerformed
        // GERANDO RELATORIO DE AGENDAMENTOS
        int confirma = JOptionPane.showConfirmDialog(rootPane, "DESEJA REALMENTE IMPRIMIR?", "ATENÇÃO!",JOptionPane.YES_NO_OPTION);//confirmacao de impressao
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo relatorio com iReport
            try {
                //Usando a class JasperPrint para preparar a impressao relatorio
                JasperPrint print = JasperFillManager.fillReport("D:/NetBeansProjects/Cardio Itaim/src/br/com/cardioitaim/ireports/relAgendamentos.jasper",null,conn);
                //a linha abaixo exibe o relatorio atraves da classe JasperViewer
                JasperViewer.viewReport(print,false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_jMenuItemRelAgendamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonAgendamento;
    private javax.swing.JButton jButtonCadMedicos;
    private javax.swing.JButton jButtonCadPacientes;
    private javax.swing.JButton jButtonCadUsuarios;
    private javax.swing.JButton jButtonDeslogar;
    private javax.swing.JInternalFrame jInternalFramePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoBemVindo;
    private javax.swing.JLabel jLabelInfoAgenda;
    private javax.swing.JLabel jLabelInfoAgendamento;
    private javax.swing.JLabel jLabelInfoDeslogar;
    private javax.swing.JLabel jLabelInfoMedicos;
    private javax.swing.JLabel jLabelInfoUsuario;
    private javax.swing.JLabel jLabelInfoUsuarios;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelinfoPacientes1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemAgendamentos;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemDeslogar;
    private javax.swing.JMenuItem jMenuItemPacientes;
    private javax.swing.JMenuItem jMenuItemRelAgendam;
    private javax.swing.JMenuItem jMenuItemRelPacientes;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenuItem jMenuMedicos;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JLabel lblIconeTelaprincipal;
    private javax.swing.JLabel lblTelaFundo;
    private javax.swing.JLabel lblTituloBemVindo;
    private javax.swing.JLabel lblTituloTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
